services:
  python:
    build:
      context: ./python
    restart: always
    devices:
       - /dev/ttyUSB0:/dev/ttyUSB0
    privileged: true
    depends_on: [influxdb, mosquitto]
    volumes:
      - ./python:/usr/src/app
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./influxdb/init:/docker-entrypoint-initdb.d
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME} # sourced from .env
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD} # sourced from .env

  grafana:
    restart: always
    image: grafana/grafana:9.0.8
    ports:
      - 3000:3000
    volumes:
      - ./grafana/lib:/var/lib/grafana
      - ./grafana/etc:/etc/grafana
      - ./grafana/log:/var/log/grafana

  mosquitto:
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
      - 9001:9001


